### ISSUE TITLE
Implement e2e test using CAPD and kind

### ISSUE THREAD

**Issue by chrischdi** [mercedes-benz/cluster-api-state-metrics#1]
CI currently only executes unit tests.

Similar to Cluster API another github action could:
* create a kind cluster
* deploy capd to kind cluster
* deploy casm to kind cluster
* deploy a cluster using capd
* check if entries for all metrics exist

<sup>
Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH, 
<a href="https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md">Provider Information</a>
</sup>

**Comment by johannesfrey** [comment]
Closing due to project being archived: https://github.com/mercedes-benz/cluster-api-state-metrics/issues/34
