### ISSUE TITLE
Add kubeadmControlPlane status.condition metric

### ISSUE THREAD

**Issue by mehyedes** [mercedes-benz/cluster-api-state-metrics#11]
Just like for machines, where we have the metric `capi_machine_status_condition`, I believe it might be useful to add a similar metric `capi_kubeadmcontrolplane_status_condition` for kubeadmControlPlanes as it provides more visibility about the actual state of the CP and would be really handy when configuring related alerts.

What do you think?

**Comment by chrischdi** [comment]
Sounds good and seems to be an important information :+1:
