### ISSUE TITLE
Remove deprecated klog flags

### ISSUE THREAD

**Issue by seanschneeweiss** [mercedes-benz/cluster-api-state-metrics#22]
With K8s v1.23 many klog flags are deprecated.
Reference: https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#klog

We should consider to replace the following:
https://github.com/mercedes-benz/cluster-api-state-metrics/blob/412d937b661ed0a90490da663dbc8335c8aab495/deploy/chart/templates/deployment.yaml#L39-L69

**Comment by pat-glitch** [comment]
/ assign

**Comment by johannesfrey** [comment]
Closing due to project being archived: https://github.com/mercedes-benz/cluster-api-state-metrics/issues/34
