### ISSUE TITLE
Find a proper destination registry

### ISSUE THREAD

**Issue by chrischdi** [mercedes-benz/cluster-api-state-metrics#3]
Pulling images from githubs package registry requires authentication.

Because of that `make deploy` does not work out of the box.

Alternatives would be for example:
- quay.io
- hub.docker.com

We have to first determine Daimler internally what would be okay to use for us as team.

Workaround:
```
REGISTRY=my-registry/repository make image
REGISTRY=my-registry/repository make push
sed -i 's@docker.pkg.github.com/daimler/cluster-api-state-metrics@registry.app.corpintra.net/schloc@g' config/default/kustomization.yaml
sed -i "s/latest/$(git describe --tags --exact-match 2>/dev/null || git rev-parse HEAD)/" config/default/kustomization.yaml
make deploy
```

<sup>
Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH, 
<a href="https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md">Provider Information</a>
</sup>

**Comment by johannesfrey** [comment]
Closing due to project being archived: https://github.com/mercedes-benz/cluster-api-state-metrics/issues/34
