### ISSUE TITLE
Add helm chart

### ISSUE THREAD

**Issue by mehyedes** [mercedes-benz/cluster-api-state-metrics#9]
At the moment, the only way to deploy is to use `make deploy`(or `kubectl apply`). However, it would be really great if there was a helm chart available for the project.

Since we have been using the project for some time, we have already built a helm chart internally. So, I would be happy to work on this.

Let me know your thoughts about this :slightly_smiling_face:

**Comment by chrischdi** [comment]
Hi @mehyedes ,

Having a helm chart would be great 👍
I'd be happy to accept a Pull Request for it.

Please keep i mind that I am required to check if you have signed our CLA https://github.com/mercedes-benz/cluster-api-state-metrics/blob/master/CONTRIBUTING.md#cla to accept a PR. If you have any issues / legal questions or other things regarding that feel free to ping me here or on slack so we could improve then on our side 😊

**Comment by mehyedes** [comment]
Great. No problem. I have already sent the signed CLA to the mentioned email address. Please let me know if there are any issues with it.

**Comment by chrischdi** [comment]
Should be fine then, thank you 👍
